name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.19
        env:
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - ${{ vars.DB_PORT }}:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Setup the database
      run: |
        export PGPASSWORD=${{ secrets.DB_PASSWORD }}
        pg_restore -h ${{ vars.DB_HOST }} -p ${{ vars.DB_PORT }} -U ${{ vars.DB_USER }} -d ${{ vars.DB_NAME }}  ./test-data/booking.tar
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install dotenv-cli
      run: npm i -g dotenv-cli
    - name: Run Playwright tests
      run: dotenv -e ./test-data/.env.sample -v password=${{ secrets.password }} -v username=${{ secrets.username }}  -v DB_HOST=${{ vars.DB_HOST }} -v DB_PORT=${{ vars.DB_PORT }} -v DB_NAME=${{ vars.DB_NAME }} -v DB_USER=${{ vars.DB_USER }} -v DB_PASSWORD=${{ secrets.DB_PASSWORD }} -- npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
