name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.19
        env:
          POSTGRES_DB: booking_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: My:s3Cr3t/
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: setup the database
      run: pg_restore -h localhost -p 5432 -U postgres -d booking_db  ./test-data/booking.tar
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install dotenv-cli
      run: npm i -g dotenv-cli
    - name: Run Playwright tests
      run: dotenv -e ./test-data/.env.sample -v password=${{ secrets.password }} -v username=${{ secrets.username }}  -- npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
